# Generated by Django 4.1.7 on 2023-02-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'IllustrationModel'), (2, 'Text')], verbose_name='Type')),
                ('like', models.PositiveSmallIntegerField(verbose_name='Like')),
                ('dislike', models.PositiveSmallIntegerField(verbose_name='Dislike')),
            ],
        ),
        migrations.CreateModel(
            name='IllustrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='jpg,png', upload_to='images', verbose_name='image')),
                ('tag', models.PositiveSmallIntegerField(choices=[(1, 'NovelAI'), (2, 'DALL.E'), (3, 'Stable Diffusion'), (4, 'Midjourney')], verbose_name='tag')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('seed', models.CharField(max_length=120, verbose_name='Seed')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('tag', models.PositiveSmallIntegerField(choices=[(1, 'NovelAI'), (2, 'ChatGPT'), (3, 'Jasper'), (4, 'Other')], verbose_name='tag')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
