# Generated by Django 4.1.7 on 2023-02-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='dislike',
            new_name='ai',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='like',
            new_name='human',
        ),
    ]
