# Generated by Django 4.1.7 on 2023-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_illustrationcommentmodel_textcommentmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcommentmodel',
            name='ai',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='AI'),
        ),
        migrations.AlterField(
            model_name='textcommentmodel',
            name='human',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Human'),
        ),
    ]
