# Generated by Django 4.1.7 on 2023-02-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_textcommentmodel_ai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustrationcommentmodel',
            name='ai',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='AI'),
        ),
        migrations.AlterField(
            model_name='illustrationcommentmodel',
            name='human',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Human'),
        ),
    ]
